### ISSUE TITLE
Invoking the plugin from vue UI never ends.

### ISSUE THREAD

**Issue by peerhenry** [jaeming/vue-cli-plugin-pug#4]
Issue:
After installing the plugin with Vue UI, the plugin is invoked but never finishes.

Steps to reproduce:
- Use Vue UI to create a vanilla Vue project.
- Add vue-cli-plugin-pug from the Vue UI.
- The UI reaches the following screen:
![vue-cli-plugin-pug-1](https://user-images.githubusercontent.com/8089487/59553585-13691c00-8f97-11e9-9cc2-094aa1ace9a3.png)
- Invoking never finishes

There appear to be a bunch of 404's:
![vue-cli-plugin-pug-2](https://user-images.githubusercontent.com/8089487/59553590-2380fb80-8f97-11e9-9b5e-84a38bef873a.png)

**Comment by jaeming** [comment]
this is because unpkg.com was down I'm guessing. It looks like all of your dependencies were 404 (not found). This plug in does not have any reference to unpkg.com.
