### ISSUE TITLE
Feature Request: Add a Generator

### ISSUE THREAD

**Issue by smhmd** [jaeming/vue-cli-plugin-pug#7]
`Plugin vue-cli-plugin-pug does not have a generator to invoke` the terminal outputs. I think replacing 
```html
<template>
  <div id="app">
    <img alt="Vue logo" src="./assets/logo.png">
    <HelloWorld msg="Welcome to Your Vue.js App"/>
  </div>
</template>
```
with
```pug
<template>
  #app
    img(alt='Vue logo' src='./assets/logo.png')
    HelloWorld(msg='Welcome to Your Vue.js App')
</template>
```
as well as the template tag of `HelloWorld.vue` would be nice.

**Comment by jaeming** [comment]
I think this over-reaches the scope of what I initially wanted to accomplish. It feels like something that could be brittle.
